openapi: 3.0.3
info:
  title: Todo Chatbot API
  description: API contract for the Todo Chatbot application deployed in Kubernetes
  version: 1.0.0
  contact:
    name: Development Team
    email: team@example.com
servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://backend-service.default.svc.cluster.local:8000
    description: Internal Kubernetes service URL

paths:
  /api/{user_id}/todos:
    get:
      summary: Get all todos for a user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The user ID
      responses:
        '200':
          description: List of todos for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized
        '404':
          description: User not found
      security:
        - bearerAuth: []

    post:
      summary: Create a new todo for a user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The user ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized
        '400':
          description: Invalid input

  /api/{user_id}/todos/{todo_id}:
    get:
      summary: Get a specific todo
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Todo details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized
        '404':
          description: Todo not found

    put:
      summary: Update a todo
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized
        '404':
          description: Todo not found

    delete:
      summary: Delete a todo
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Todo deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Todo not found

  /api/{user_id}/chat:
    post:
      summary: Send a message to the AI chatbot
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The user ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's message to the chatbot
                conversation_id:
                  type: string
                  description: Optional conversation ID to continue a conversation
      responses:
        '200':
          description: AI response to the user's message
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The AI's response
                  conversation_id:
                    type: string
                    description: The conversation ID for continued conversation
                  action:
                    type: string
                    description: Optional action to perform (e.g., "create_todo", "update_todo")
                  action_data:
                    type: object
                    description: Additional data for the action
        '401':
          description: Unauthorized

components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - user_id
        - completed
      properties:
        id:
          type: string
          description: Unique identifier for the todo
        title:
          type: string
          description: Title of the todo
        description:
          type: string
          description: Optional description of the todo
        completed:
          type: boolean
          description: Whether the todo is completed
        user_id:
          type: string
          description: ID of the user who owns this todo
        created_at:
          type: string
          format: date-time
          description: When the todo was created
        updated_at:
          type: string
          format: date-time
          description: When the todo was last updated

    TodoCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Title of the todo
        description:
          type: string
          description: Optional description of the todo
        completed:
          type: boolean
          default: false
          description: Whether the todo is completed (defaults to false)

    TodoUpdate:
      type: object
      properties:
        title:
          type: string
          description: Updated title of the todo
        description:
          type: string
          description: Updated description of the todo
        completed:
          type: boolean
          description: Updated completion status

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT